'use client';
import {ResponsiveContainer,BarChart,Bar,Cell,XAxis,YAxis,Tooltip,CartesianGrid,LineChart,Line,Legend} from 'recharts';
import {useReducedMotion} from 'motion/react';
import {money,integer,type Row} from '@petshop/analytics';
const palette=['var(--chart-primary)','var(--chart-accent)','var(--chart-teal)','var(--chart-secondary)','var(--chart-pink)'];
const short=(v:number)=>Math.abs(v)>=1000?`${(v/1000).toLocaleString('pt-BR',{maximumFractionDigits:0})} mil`:String(v);
export function TrendChart({rows,ano}:{rows:Row[];ano:number}){
 const reduced=useReducedMotion();const points=[1,2,3].map(q=>({name:`${q}º quadr.`,atual:rows.find(r=>Number(r.ano)===ano&&Number(r.quadrimestre)===q)?.receita??null,anterior:rows.find(r=>Number(r.ano)===ano-1&&Number(r.quadrimestre)===q)?.receita??null}));
 return <div className="chart" aria-label={`Receita por quadrimestre, ${ano} e ${ano-1}`}><ResponsiveContainer width="100%" height="100%"><LineChart data={points} margin={{top:15,right:22,left:0,bottom:5}}><CartesianGrid vertical={false} stroke="var(--line)" strokeDasharray="3 5"/><XAxis dataKey="name" axisLine={false} tickLine={false} tick={{fontSize:12,fill:'var(--muted)'}} dy={12}/><YAxis axisLine={false} tickLine={false} tickFormatter={short} tick={{fontSize:12,fill:'var(--muted)'}} width={55}/><Tooltip formatter={v=>money(v)} contentStyle={{border:'1px solid #e6ebe8',borderRadius:12,fontSize:12}}/><Legend verticalAlign="top" align="right" iconType="circle" iconSize={7} wrapperStyle={{fontSize:12,paddingBottom:18}}/><Line name={String(ano-1)} dataKey="anterior" stroke="var(--chart-secondary)" strokeWidth={2} strokeDasharray="5 5" dot={{r:3}} isAnimationActive={!reduced}/><Line name={String(ano)} dataKey="atual" stroke="var(--chart-primary)" strokeWidth={3} dot={{r:5,strokeWidth:3,stroke:'var(--surface)'}} activeDot={{r:7}} isAnimationActive={!reduced}/></LineChart></ResponsiveContainer></div>;
}
export function HorizontalChart({rows,label,metric='receita',color}:{rows:Row[];label:string;metric?:string;color?:string}){
 const reduced=useReducedMotion();const selected=[...rows].sort((a,b)=>Number(b[metric])-Number(a[metric])||String(a[label]).localeCompare(String(b[label]),'pt-BR')).slice(0,5);
 return <div className="chart horizontal" aria-label={`${metric==='quantidade'?'Quantidade':'Receita'} por ${label}`}><ResponsiveContainer width="100%" height="100%"><BarChart data={selected} layout="vertical" margin={{top:5,right:16,bottom:4,left:0}}><CartesianGrid horizontal={false} stroke="var(--line)"/><XAxis type="number" axisLine={false} tickLine={false} tickFormatter={short} tick={{fontSize:12,fill:'var(--muted)'}}/><YAxis type="category" dataKey={label} width={140} axisLine={false} tickLine={false} tick={{fontSize:12,fill:'var(--ink)'}} tickFormatter={(v:string)=>v.length>24?v.slice(0,23)+'…':v}/><Tooltip formatter={v=>metric==='quantidade'?integer(v):money(v)} cursor={{fill:'var(--surface-soft)'}} contentStyle={{borderRadius:12,fontSize:12}}/><Bar dataKey={metric} name={metric==='quantidade'?'Unidades':'Receita'} fill={color??'var(--chart-primary)'} radius={[0,5,5,0]} maxBarSize={21} isAnimationActive={!reduced}>{selected.map((row,index)=><Cell key={String(row[label])} fill={color??palette[index%palette.length]}/>)}</Bar></BarChart></ResponsiveContainer></div>;
}
export function CompetitorChart({rows}:{rows:Row[]}){
 const reduced=useReducedMotion();const data=rows.filter(r=>Number(r.quadrimestre)>0).sort((a,b)=>Number(a.quadrimestre)-Number(b.quadrimestre)).map(r=>({...r,name:`${r.quadrimestre}º quadr.`}));
 return <div className="chart"><ResponsiveContainer width="100%" height="100%"><BarChart data={data}><CartesianGrid vertical={false} stroke="var(--line)"/><XAxis dataKey="name" axisLine={false} tickLine={false} tick={{fontSize:12,fill:'var(--muted)'}}/><YAxis tickFormatter={short} axisLine={false} tickLine={false} tick={{fontSize:12,fill:'var(--muted)'}} width={55}/><Tooltip formatter={v=>money(v)}/><Legend iconType="circle" iconSize={8} wrapperStyle={{fontSize:12}}/><Bar dataKey="receita_rede" name="Nosso Aumigo" fill="var(--chart-primary)" radius={[5,5,0,0]} maxBarSize={40} isAnimationActive={!reduced}/><Bar dataKey="receita_concorrente" name="Concorrente" fill="var(--chart-accent)" radius={[5,5,0,0]} maxBarSize={40} isAnimationActive={!reduced}/></BarChart></ResponsiveContainer></div>;
}
