'use client';
import {useRef,useState,useEffect} from 'react';
import {Sparkles,X,Send,ArrowUpRight} from 'lucide-react';
import {periodLabel,storeLabel,type Filters} from '@petshop/analytics';
type Message={role:'user'|'assistant';content:string};
export default function Chat({filters,available}:{filters:Filters;available:boolean}){
 const dialog=useRef<HTMLDialogElement>(null);const bottom=useRef<HTMLDivElement>(null);const [messages,setMessages]=useState<Message[]>([]);const [input,setInput]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState('');
 useEffect(()=>{setMessages([]);setError('');},[filters.ano,filters.quadrimestre,filters.loja]);
 useEffect(()=>{bottom.current?.scrollIntoView({block:'nearest'});},[messages,busy]);
 async function send(value=input){if(!value.trim()||busy||!available)return;const next=[...messages,{role:'user' as const,content:value.trim()}];setMessages(next);setInput('');setBusy(true);setError('');try{const response=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({messages:next.slice(-10),filters}),signal:AbortSignal.timeout(45000)});const result=await response.json();if(!response.ok)throw new Error(result.error);setMessages([...next,{role:'assistant',content:result.answer}]);}catch(e){setError(e instanceof Error?e.message:'Não foi possível responder agora.');}finally{setBusy(false);}}
 return <><button className="assistant-trigger" onClick={()=>dialog.current?.showModal()}><Sparkles size={17}/><span>Pergunte aos dados</span><ArrowUpRight size={15}/></button><dialog ref={dialog} className="chat-dialog"><div className="chat-head"><div><span className="eyebrow">SEU ASSISTENTE</span><h2>Uma conversa com os dados.</h2></div><button className="icon-button" aria-label="Fechar assistente" onClick={()=>dialog.current?.close()}><X/></button></div><div className="chat-context">{periodLabel(filters)} · {storeLabel(filters.loja)}</div><div className="chat-messages">{!available?<div className="chat-empty"><Sparkles size={28}/><h3>Estamos preparando o assistente.</h3><p>A integração ainda não está disponível. Você já pode explorar todos os indicadores do painel.</p></div>:messages.length===0?<div className="chat-empty"><Sparkles size={28}/><h3>Qual é a sua próxima pergunta?</h3><p>Explore resultados e simule possibilidades com premissas claras.</p>{['O que explica o resultado deste período?','Quais produtos merecem atenção?','Simule uma receita 10% maior neste período.'].map(q=><button key={q} onClick={()=>send(q)}>{q}<ArrowUpRight size={15}/></button>)}</div>:messages.map((m,i)=><div key={i} className={`message ${m.role}`}><small>{m.role==='user'?'Você':'Assistente Nosso Aumigo'}</small><p>{m.content}</p></div>)}{busy&&<p role="status" className="chat-thinking">Consultando os indicadores…</p>}{error&&<p className="form-error" role="alert">{error}</p>}<div ref={bottom}/></div><form noValidate className="chat-form" onSubmit={e=>{e.preventDefault();send();}}><label className="sr-only" htmlFor="chat-question">Sua pergunta</label><input id="chat-question" value={input} onChange={e=>setInput(e.target.value)} disabled={!available||busy} maxLength={1500} placeholder="Pergunte sobre o negócio…"/><button className="icon-button" disabled={!available||busy||!input.trim()} aria-label="Enviar pergunta"><Send size={18}/></button></form><p className="chat-disclaimer">Cenários são simulações, não garantias de resultados.</p></dialog></>;
}
